var res = {
    font : {
        type : "font",
        name : "Pribambas",
        srcs : ["res/fonts/Pribambas.eot", "res/fonts/Pribambas.ttf"]
    },

    cursor : "res/cursor.png",
    
    // Layer_363_png : "res/playground/Layer_363.png",
    // decor_flags_png : "res/playground/decor_flags.png",
    // idol_bear_png : "res/playground/idol_bear.png",
    // idol_shrooms_png : "res/playground/idol_shrooms.png",
    // idol_shrooms_noworm_png : "res/playground/idol_shrooms_noworm.png",
    // Layer_362_png : "res/playground/Layer_362.png",
    // decor_steps_png : "res/playground/decor_steps.png",
    // play_gorka_png : "res/playground/play_gorka.png",
    // idol_croc_png : "res/playground/idol_croc.png",
    // idol_keykeeper_png : "res/playground/idol_keykeeper.png",
    // decor_dino_png : "res/playground/decor_dino.png",
    // decor_dino_open_png : "res/playground/decor_dino_open.png",
    // play_swing_png : "res/playground/play_swing.png",
    // decor_tires_png : "res/playground/decor_tires.png",
    // idol_horse_png : "res/playground/idol_horse.png",
    // idol_yaga_png : "res/playground/idol_yaga.png",
    // decor_bushesnsticks_png : "res/playground/decor_bushesnsticks.png",
    // idol_hare_png : "res/playground/idol_hare.png",
    // decor_streetlamp_png : "res/playground/decor_streetlamp.png",
    // decor_streetlamp_2_png : "res/playground/decor_streetlamp_2.png",
    // decor_umbrella_png : "res/playground/decor_umbrella.png",
    // decor_fence_png : "res/playground/decor_fence.png",
    // forest_png : "res/playground/forest.png",
    // sky_png : "res/playground/sky.png",
    // ground_png : "res/playground/ground.png",
    
    playground_plist : "res/playground.plist",
    playground_png : "res/playground.png",

    back : "res/prologue/playground_back_00.jpg",
    prologue_arrow : "res/prologue/prologue_arrow.png",
    text_box : "res/dialog_square.png",

    playground_json : "res/playground.json",

    lamp : "res/sounds/lamp_drone.wav",
    prologue_theme : "res/sounds/prologue_crickets.mp3",
    playground_theme : "res/sounds/playground_theme.mp3",
    angry_theme : "res/sounds/scene_angry_music.mp3",
    culmination_theme : "res/sounds/scene_culmination_music.mp3",
    culmination_enter : "res/sounds/culmination_entrance.wav",
    culmination_loop : "res/sounds/culmination_loop.wav",
    typing_1 : "res/sounds/typing_1.wav",
    typing_2 : "res/sounds/typing_2.wav",
    typing_3 : "res/sounds/typing_3.wav",
    step_1 : "res/sounds/step_1.wav",
    step_2 : "res/sounds/step_2.wav",
    swing : "res/sounds/swing.wav",
    croc_jump: "res/sounds/croco_jumping.wav",
    fin_pose : "res/sounds/fin_pose.wav",
    fracture_fin : "res/sounds/keykeeper_fractured_fin.wav",
    fracture : "res/sounds/keykeeper_fractured.wav",
    mustache_left : "res/sounds/keykeeper_mustache_left.wav",
    mustache_right : "res/sounds/keykeeper_mustache_right.wav",
    nose : "res/sounds/keykeeper_nose.wav",
    slide_down: "res/sounds/slide_down.wav",
    letter_1 : "res/sounds/Letter_1.wav",
    letter_2 : "res/sounds/Letter_2.wav",
    letter_3 : "res/sounds/Letter_3.wav",
    letter_4 : "res/sounds/Letter_4.wav",
    letter_5 : "res/sounds/Letter_5.wav",
    letter_wrong : "res/sounds/Letter_wrong.wav",
    letter_success : "res/sounds/Letters_success.wav",
    saw_sound : "res/sounds/sound_saw.wav",
    door : "res/sounds/door.wav",
    idle_2 : "res/sounds/idle_2.wav",
    idle_3 : "res/sounds/idle_3.wav",
    action : "res/sounds/action.wav",
    step_event_1 : "res/sounds/step_event_1.wav",
    step_event_2 : "res/sounds/step_event_2.wav",
    step_event_3 : "res/sounds/step_event_3.wav",
    step_event_4 : "res/sounds/step_event_4.wav",
    step_event_5 : "res/sounds/step_event_5.wav",
    step_event_6 : "res/sounds/step_event_6.wav",
    step_event_7 : "res/sounds/step_event_7.wav",
    step_event_8 : "res/sounds/step_event_8.wav",
    step_event_9 : "res/sounds/step_event_9.wav",
    
    actions_plist : "res/animations/actions.plist",
    actions_png : "res/animations/actions.png",
    walk_plist : "res/animations/walk.plist",
    walk_png : "res/animations/walk.png",
    idle_1_plist : "res/animations/idle_1.plist",
    idle_1_png : "res/animations/idle_1.png",
    idle_2_plist : "res/animations/idle_2.plist",
    idle_2_png : "res/animations/idle_2.png",
    idle_3_plist : "res/animations/idle_3.plist",
    idle_3_png : "res/animations/idle_3.png",
    slide_1_plist : "res/animations/slide-1.plist",
    slide_1_png : "res/animations/slide-1.png",
    slide_2_plist : "res/animations/slide-2.plist",
    slide_2_png : "res/animations/slide-2.png",
    croc_plist : "res/animations/croc.plist",
    croc_png : "res/animations/croc.png",
    keykeeper_1_plist : "res/animations/keykeeper-1.plist",
    keykeeper_1_png : "res/animations/keykeeper-1.png",
    keykeeper_2_plist : "res/animations/keykeeper-2.plist",
    keykeeper_2_png : "res/animations/keykeeper-2.png",
    moth_plist : "res/animations/moth.plist",
    moth_png : "res/animations/moth.png",
    ants_plist : "res/animations/ants.plist",
    ants_png : "res/animations/ants.png",
    shroom_bug_plist : "res/animations/shroom_bug.plist",
    shroom_bug_png : "res/animations/shroom_bug.png",
    
    lamp_plist : "res/animations/lamp.plist",
    lamp_png : "res/animations/lamp.png",
    swing_plist : "res/animations/swing.plist",
    swing_png : "res/animations/swing.png",
    
    look : "res/icons/look.png",
    use : "res/icons/use.png",
    key : "res/icons/key.png",
    saw : "res/icons/saw.png",
    inventory_key : "res/icons/inventory_key.png",
    inventory_saw : "res/icons/inventory_saw.png",

    titles_blank : "res/titles/titles_blank.jpg",
    titles_0 : "res/titles/titles_00.jpg",
    titles_1 : "res/titles/titles_01.jpg",
    titles_2 : "res/titles/titles_02.jpg",
    titles_3 : "res/titles/titles_03.jpg"
    
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
